---
- name: "install python."
  become: yes
  apt:
    name: python3
    state: latest
    update_cache: yes

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages."
  become: yes
  apt:
    upgrade: yes
- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
- name: "configure node exporter"
  become: true
  shell: |
    useradd --no-create-home node_exporter
    wget https://github.com/prometheus/node_exporter/releases/download/v1.4.0-rc.0/node_exporter-1.4.0-rc.0.linux-amd64.tar.gz
    tar xzf node_exporter-1.4.0-rc.0.linux-amd64
    cp node_exporter-1.4.0-rc.0.linux-amd64/node_exporter /usr/local/bin/node_exporter
    echo "
    [Unit]
    Description=Prometheus Node Exporter Service
    After=network.target

    [Service]
    User=node_exporter
    Group=node_exporter
    Type=simple
    ExecStart=/usr/local/bin/node_exporter

    [Install]
    WantedBy=multi-user.target" >> /etc/systemd/system/node-exporter.service
    cat /etc/systemd/system/node-exporter.service
    systemctl daemon-reload
    systemctl enable node-exporter
    systemctl start node-exporter
    systemctl status node-exporter
