- name: Unpacking zipped files
  unarchive:
    src: artifact.tar.gz
    dest: .
- name: Executing node
  shell: |
    tar -xf artifact.tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start
